<?php
/**
 * Created by PhpStorm.
 * User: Nitish Kumar
 * Date: 8/10/2018
 * Time: 9:38 AM
 */

class Session extends SessionHandler
{
    private $fich;

    public function __construct($fich)
    {
        $this->fich = $fich;
    }

    public function close()
    {
        $this->log('close');
        parent::close(); // TODO: Change the autogenerated stub
    }

}